### ISSUE TITLE
Feedback Sprint 1 Datadashboard

### ISSUE THREAD

**Issue by nerdale** [ninagallo/cdmx-2018-06-bc-core-am-data-dashboard#4]
Hola @ninagallo y @SakuraBravo 
He estado revisando el proyecto y tengo algunos comentarios:

1. Que pasó con el deploy en GithubPages? era requisito en el demo del sprint 1

2. Buen trabajo y completo de investigación del usuario, se nota la dedicación e interés en saber las necesidades exactas del usuario :clap: me encantó poder ver la interacción en el prototipo de alta fidelidad, felicitaciones :rocket: 

3. Cuando en el test dice `debería exponer función computeStudentsStats en objeto global` quiere decir que **computeStudentsStats** que tiene la siguiente estructura `window.computeStudentsStats`

4. Recuerden utilizar HTML semántico `<header></header> <section></section> <aside></aside> <footer></footer> <article></article>`

5.  Si bien ya tienen algo de lógica adelantado, les recomiendo comenzar a trabajar con la data a full lo antes posible (se encontrarán con toda la lógica para jalar la información y hacer los cálculos) y plasmar tanto visual como funcionalmente lo que tienen pensado para el proyecto.

Go go go!! you can do it!! :muscle:

**Comment by SakuraBravo** [comment]
¡¡Gracias Alexandra!!

Le seguimos echando muchas ganas.

**Comment by nerdale** [comment]
Perfecto, daré por cerrado el issue :smile: 
:rocket:
